import type { Task } from '@/types'

export const tasks = [
  {
    id: 't1',
    title: 'Ana Sayfa Hero Alanı Tasarımı',
    project: 'Ankara Gurme - Web Yenileme',
    projectId: 'p1',
    assignedTo: 'Admin',
    priority: 'High',
    status: 'In Progress',
    dueDate: '2024-05-18',
  },
  {
    id: 't2',
    title: 'Ürün Filtre Bileşeni',
    project: 'İstanbul Mode - E-ticaret',
    projectId: 'p2',
    assignedTo: 'Admin',
    priority: 'High',
    status: 'In Progress',
    dueDate: '2024-05-20',
  },
  {
    id: 't3',
    title: 'Anahtar Kelime Raporu - Mayıs',
    project: 'Bursa Hukuk - SEO Kampanyası',
    projectId: 'p3',
    assignedTo: 'Admin',
    priority: 'Medium',
    status: 'Review',
    dueDate: '2024-05-16',
  },
  {
    id: 't4',
    title: 'QR Menü İçerik Güncellemesi',
    project: 'Ankara Gurme - QR Menü v2',
    projectId: 'p4',
    assignedTo: 'Admin',
    priority: 'Medium',
    status: 'Done',
    dueDate: '2024-05-14',
  },
  {
    id: 't5',
    title: 'Müşteri Revizyon Geri Bildirimi',
    project: 'Bodrum Butik - Tam Paket',
    projectId: 'p5',
    assignedTo: 'Admin',
    priority: 'High',
    status: 'Todo',
    dueDate: '2024-05-17',
  },
  {
    id: 't6',
    title: 'Ödeme Altyapısı Entegrasyonu',
    project: 'İstanbul Mode - E-ticaret',
    projectId: 'p2',
    assignedTo: 'Admin',
    priority: 'High',
    status: 'Todo',
    dueDate: '2024-05-22',
  },
  {
    id: 't7',
    title: 'Google Analytics Kurulumu',
    project: 'Bursa Hukuk - SEO Kampanyası',
    projectId: 'p3',
    assignedTo: 'Admin',
    priority: 'Low',
    status: 'Blocked',
    dueDate: '2024-05-12',
  },
  {
    id: 't8',
    title: 'Otel Oda Sayfaları İçeriği',
    project: 'Bodrum Butik - Tam Paket',
    projectId: 'p5',
    assignedTo: 'Admin',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: '2024-05-19',
  },
  {
    id: 't9',
    title: 'Sezonluk Menü Fotoğraf Çekimi',
    project: 'Trabzon Balık - QR Menü',
    projectId: 'p6',
    assignedTo: 'Admin',
    priority: 'Low',
    status: 'Todo',
    dueDate: '2024-05-21',
  },
] satisfies Task[]
