import type { Note } from '@/types'

export const notes = [
  {
    id: 'n1',
    title: 'Bodrum Butik - Revizyon Geri Bildirimi',
    category: 'Revision Requests',
    related: 'Bodrum Butik Otel',
    relatedType: 'client',
    content: 'Müşteri hero alanını daha koyu, logoyu daha büyük ve rezervasyon butonunu daha belirgin istiyor. Teslim tarihi 1 Haziran’a uzatıldı.',
    updatedAt: '2024-05-15',
    tags: ['revizyon', 'acil'],
  },
  {
    id: 'n2',
    title: 'Toplantı Notu - İstanbul Mode 14 Mayıs',
    category: 'Meeting Notes',
    related: 'İstanbul Mode Store',
    relatedType: 'client',
    content: 'Ürün fotoğraf yükleme akışı görüşüldü. Müşteri 20 Mayıs’a kadar 300 ürün görseli paylaşacak. Ödeme altyapısı kararı: İyzico.',
    updatedAt: '2024-05-14',
    tags: ['toplanti', 'e-ticaret'],
  },
  {
    id: 'n3',
    title: 'Yeni Hizmet Fiyatlandırma - QR Menü 2024',
    category: 'Internal Ideas',
    related: null,
    relatedType: 'internal',
    content: 'Yeni müşteriler için QR Menü başlangıç fiyatı ₺4.500 düşünülebilir. Alerjen bilgisini varsayılan özellik yap. 1 ay hosting ile paketlenebilir.',
    updatedAt: '2024-05-12',
    tags: ['fiyat', 'strateji'],
  },
  {
    id: 'n4',
    title: 'Mersin Oto Galeri - Müşteri Notları',
    category: 'Client Notes',
    related: 'Mersin Oto Galeri',
    relatedType: 'client',
    content: 'LinkedIn üzerinden geldi. Stok listeleme sistemli galeri sitesi istiyor. Bütçe esnek. Mayıs sonu tekrar takip edilecek.',
    updatedAt: '2024-05-13',
    tags: ['potansiyel', 'takip'],
  },
  {
    id: 'n5',
    title: 'Q3 Büyüme Stratejisi',
    category: 'Internal Ideas',
    related: null,
    relatedType: 'internal',
    content: 'Bodrum ve Antalya konaklama sektörüne odaklan. Web + QR + SEO paketini ₺25.000 sabit fiyatla çıkar. Referans programı oluştur.',
    updatedAt: '2024-05-11',
    tags: ['strateji', 'buyume'],
  },
  {
    id: 'n6',
    title: 'Bursa Hukuk - SEO İlerleme',
    category: 'Client Notes',
    related: 'Bursa Hukuk Bürosu',
    relatedType: 'client',
    content: '12 hedef anahtar kelimede sıralama yükseldi. "Bursa avukat" şu an 4. sırada. Blog içerikleri aylık 2 adede çıkarılmalı.',
    updatedAt: '2024-05-10',
    tags: ['seo', 'ilerleme'],
  },
] satisfies Note[]
