import type { Service } from '@/types'

export const services = [
  {
    id: 's1',
    name: 'Web Tasarım',
    icon: 'Globe',
    description: 'Dönüşüm ve marka etkisi için özel, responsive web siteleri.',
    startingPrice: 8000,
    currency: '₺',
    delivery: '3-6 hafta',
    includes: ['UI/UX Tasarım', 'Responsive Geliştirme', 'CMS Entegrasyonu', 'Temel SEO Kurulumu', '1 Ay Destek'],
    addons: ['E-ticaret Modülü', 'Çoklu Dil', 'Özel Animasyonlar'],
    color: 'blue',
  },
  {
    id: 's2',
    name: 'SEO',
    icon: 'TrendingUp',
    description: 'Organik görünürlük ve sıralama için veri odaklı SEO stratejisi.',
    startingPrice: 2000,
    currency: '₺',
    delivery: 'Aylık retainer',
    includes: ['Anahtar Kelime Araştırması', 'Sayfa İçi Optimizasyon', 'Aylık Raporlar', 'Backlink Stratejisi', 'Rakip Analizi'],
    addons: ['İçerik Yazımı', 'Google Ads Yönetimi', 'Lokal SEO'],
    color: 'green',
  },
  {
    id: 's3',
    name: 'Sosyal Medya Yönetimi',
    icon: 'Instagram',
    description: 'Markanız için içerik üretimi, planlama ve topluluk yönetimi.',
    startingPrice: 7500,
    currency: '₺',
    delivery: 'Aylık retainer',
    includes: ['İçerik Stratejisi', 'Post & Reels Tasarımı', 'Metin Yazarlığı', 'Aylık Planlama', 'Performans Raporu'],
    addons: ['Reklam Yönetimi', 'Influencer İş Birlikleri', 'Profesyonel Çekim'],
    color: 'orange',
  },
  {
    id: 's4',
    name: 'E-ticaret Mağazası',
    icon: 'ShoppingBag',
    description: 'Katalogdan ödeme adımına kadar ölçeklenebilir online mağazalar.',
    startingPrice: 18000,
    currency: '₺',
    delivery: '6-10 hafta',
    includes: ['Özel Shopify/WooCommerce', 'Ödeme Entegrasyonu', 'Ürün Aktarımı', 'Stok Kurulumu', '2 Ay Destek'],
    addons: ['ERP Entegrasyonu', 'Pazaryeri Senkronu', 'Abonelik Sistemi'],
    color: 'purple',
  },
  {
    id: 's5',
    name: 'Bakım ve Destek',
    icon: 'Shield',
    description: 'Sürekli teknik destek, güncelleme ve performans izleme.',
    startingPrice: 1500,
    currency: '₺',
    delivery: 'Aylık',
    includes: ['Hata Düzeltmeleri', 'Eklenti Güncellemeleri', 'Günlük Yedekler', 'Güvenlik Taramaları', 'Aylık Rapor'],
    addons: ['Öncelikli Dönüş', 'Özellik Geliştirme', 'Performans Optimizasyonu'],
    color: 'cyan',
  },
] satisfies Service[]

