import type { Client } from '@/types'

export const clients = [
  {
    id: 'c1',
    company: 'Ankara Gurme Restoran',
    contact: 'Mehmet Yılmaz',
    email: 'mehmet@ankarag.com',
    phone: '+90 532 100 1111',
    services: ['Web Design', 'QR Menu'],
    status: 'Active',
    activeProjects: 2,
    totalPaid: 28500,
    lastContact: '2024-05-10',
    tags: ['Web Design', 'QR Menu'],
    notes: 'Haziran ayında ana sayfa revizyonu gerekiyor.',
    location: 'Ankara',
  },
  {
    id: 'c2',
    company: 'İstanbul Mode Store',
    contact: 'Ayşe Kara',
    email: 'ayse@istanbulmode.com',
    phone: '+90 544 200 2222',
    services: ['E-commerce'],
    status: 'Active',
    activeProjects: 1,
    totalPaid: 42000,
    lastContact: '2024-05-08',
    tags: ['E-commerce'],
    notes: 'Q3 döneminde Shopify geçişi planlanıyor.',
    location: 'İstanbul',
  },
  {
    id: 'c3',
    company: 'Bursa Hukuk Bürosu',
    contact: 'Kemal Öztürk',
    email: 'kemal@bursahukuk.com',
    phone: '+90 505 300 3333',
    services: ['SEO', 'Web Design'],
    status: 'Active',
    activeProjects: 1,
    totalPaid: 18200,
    lastContact: '2024-05-06',
    tags: ['SEO', 'Web Design'],
    notes: 'Aylık SEO raporları düzenli isteniyor.',
    location: 'Bursa',
  },
  {
    id: 'c4',
    company: 'Delta Mimarlık',
    contact: 'Selin Arslan',
    email: 'selin@deltamimari.com',
    phone: '+90 533 400 4444',
    services: ['Web Design'],
    status: 'In Discussion',
    activeProjects: 0,
    totalPaid: 0,
    lastContact: '2024-05-12',
    tags: ['Web Design'],
    notes: 'Portföy sitesi teklifi gönderildi.',
    location: 'İzmir',
  },
  {
    id: 'c5',
    company: 'Konya Tekstil A.Ş.',
    contact: 'Hasan Demir',
    email: 'hasan@konyatekstil.com',
    phone: '+90 512 500 5555',
    services: ['E-commerce', 'SEO'],
    status: 'Completed',
    activeProjects: 0,
    totalPaid: 35000,
    lastContact: '2024-03-20',
    tags: ['E-commerce', 'SEO'],
    notes: 'Proje teslim edildi. Arşive alındı.',
    location: 'Konya',
  },
  {
    id: 'c6',
    company: 'Trabzon Balık Evi',
    contact: 'Elif Şahin',
    email: 'elif@trabzonbalik.com',
    phone: '+90 530 600 6666',
    services: ['QR Menu'],
    status: 'Active',
    activeProjects: 1,
    totalPaid: 8500,
    lastContact: '2024-05-14',
    tags: ['QR Menu'],
    notes: 'İkinci QR menü güncellemesi gerekiyor.',
    location: 'Trabzon',
  },
  {
    id: 'c7',
    company: 'Mersin Oto Galeri',
    contact: 'Tarık Yıldız',
    email: 'tarik@mersinoto.com',
    phone: '+90 545 700 7777',
    services: ['Web Design', 'SEO'],
    status: 'Lead',
    activeProjects: 0,
    totalPaid: 0,
    lastContact: '2024-05-13',
    tags: ['Web Design', 'SEO'],
    notes: 'Tam paketle ilgileniyor.',
    location: 'Mersin',
  },
  {
    id: 'c8',
    company: 'Bodrum Butik Otel',
    contact: 'Zeynep Çelik',
    email: 'zeynep@bodrumbutik.com',
    phone: '+90 538 800 8888',
    services: ['Web Design', 'QR Menu', 'SEO'],
    status: 'Active',
    activeProjects: 3,
    totalPaid: 54000,
    lastContact: '2024-05-15',
    tags: ['Web Design', 'QR Menu', 'SEO'],
    notes: 'VIP müşteri - öncelikli destek gerekiyor.',
    location: 'Bodrum',
  },
] satisfies Client[]
