import type { Project } from '@/types'

export const projects = [
  {
    id: 'p1',
    name: 'Ankara Gurme - Web Yenileme',
    client: 'Ankara Gurme Restoran',
    clientId: 'c1',
    service: 'Web Design',
    startDate: '2024-04-01',
    deadline: '2024-05-31',
    budget: 15000,
    status: 'Design',
    priority: 'High',
    taskCount: 20,
    completedTaskCount: 11,
    description: 'Yeni marka kimliğiyle tam web sitesi yenilemesi.',
  },
  {
    id: 'p2',
    name: 'İstanbul Mode - E-ticaret',
    client: 'İstanbul Mode Store',
    clientId: 'c2',
    service: 'E-commerce',
    startDate: '2024-03-15',
    deadline: '2024-06-15',
    budget: 28000,
    status: 'Development',
    priority: 'High',
    taskCount: 30,
    completedTaskCount: 21,
    description: '500+ ürün için özel Shopify mağazası.',
  },
  {
    id: 'p3',
    name: 'Bursa Hukuk - SEO Kampanyası',
    client: 'Bursa Hukuk Bürosu',
    clientId: 'c3',
    service: 'SEO',
    startDate: '2024-01-10',
    deadline: '2024-12-31',
    budget: 12000,
    status: 'Development',
    priority: 'Medium',
    taskCount: 15,
    completedTaskCount: 6,
    description: 'Sürekli SEO ve içerik pazarlaması.',
  },
  {
    id: 'p4',
    name: 'Ankara Gurme - QR Menü v2',
    client: 'Ankara Gurme Restoran',
    clientId: 'c1',
    service: 'QR Menu',
    startDate: '2024-05-01',
    deadline: '2024-05-25',
    budget: 4500,
    status: 'Waiting for Client',
    priority: 'Medium',
    taskCount: 10,
    completedTaskCount: 9,
    description: 'Güncel menü içeriği ve QR kod yenilemesi.',
  },
  {
    id: 'p5',
    name: 'Bodrum Butik - Tam Paket',
    client: 'Bodrum Butik Otel',
    clientId: 'c8',
    service: 'Web Design',
    startDate: '2024-02-01',
    deadline: '2024-04-30',
    budget: 38000,
    status: 'Revision',
    priority: 'High',
    taskCount: 20,
    completedTaskCount: 17,
    description: 'Lüks otel için web sitesi + SEO + QR menü.',
  },
  {
    id: 'p6',
    name: 'Trabzon Balık - QR Menü',
    client: 'Trabzon Balık Evi',
    clientId: 'c6',
    service: 'QR Menu',
    startDate: '2024-05-10',
    deadline: '2024-05-22',
    budget: 3500,
    status: 'Planning',
    priority: 'Low',
    taskCount: 13,
    completedTaskCount: 2,
    description: 'Sezonluk yeni QR menü tasarımı.',
  },
  {
    id: 'p7',
    name: 'Konya Tekstil - SEO ve Mağaza',
    client: 'Konya Tekstil A.Ş.',
    clientId: 'c5',
    service: 'E-commerce',
    startDate: '2023-11-01',
    deadline: '2024-03-01',
    budget: 35000,
    status: 'Completed',
    priority: 'High',
    taskCount: 24,
    completedTaskCount: 24,
    description: 'E-ticaret + 6 aylık SEO teslim edildi.',
  },
  {
    id: 'p8',
    name: 'Bodrum Butik - SEO Retainer',
    client: 'Bodrum Butik Otel',
    clientId: 'c8',
    service: 'SEO',
    startDate: '2024-03-01',
    deadline: '2024-12-31',
    budget: 12000,
    status: 'Development',
    priority: 'Medium',
    taskCount: 10,
    completedTaskCount: 3,
    description: 'Otel görünürlüğü için aylık SEO çalışması.',
  },
] satisfies Project[]
